import re
from fpdf import FPDF
import io

def extract_skills(text):
    # Basic keyword extraction for visualization
    common_skills = [
        "python", "java", "sql", "react", "aws", "docker", "kubernetes", "machine learning",
        "data analysis", "project management", "communication", "leadership", "agile", "scrum",
        "html", "css", "javascript", "typescript", "figma", "design", "marketing", "sales",
        "finance", "accounting", "hr", "recruiting", "tensorflow", "pytorch", "pandas", "numpy",
        "c++", "c", "c#", "ruby", "go", "rust", "tableau", "power bi", "excel"
    ]
    
    found_skills = []
    text_lower = text.lower()
    
    for skill in common_skills:
        if re.search(r'\b' + re.escape(skill) + r'\b', text_lower):
            found_skills.append(skill.title())
            
    return list(set(found_skills))

# UPDATED FUNCTION SIGNATURE: Now accepts 'missing_skills' and 'category'
def generate_pdf_report(username, role, score, feedback, resume_skills, missing_skills, category):
    class PDF(FPDF):
        def header(self):
            self.set_font('Arial', 'B', 15)
            self.cell(0, 10, 'NexHire Platinum Analysis Report', 0, 1, 'C')
            self.ln(5)

        def footer(self):
            self.set_y(-15)
            self.set_font('Arial', 'I', 8)
            self.set_text_color(128)
            self.cell(0, 10, f'Generated by NexHire | Developed by Karunya K. P. | linkedin.com/in/karunyakp', 0, 0, 'C')

    pdf = PDF()
    pdf.add_page()
    
    # --- HEADER INFO ---
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 8, txt=f"Candidate: {username}", ln=True)
    pdf.cell(200, 8, txt=f"Target Role: {role}", ln=True)
    pdf.cell(200, 8, txt=f"Profile Category: {category}", ln=True) 
    pdf.ln(5)
    
    # --- SCORE ---
    pdf.set_font("Arial", 'B', size=24)
    color = (79, 70, 229) # Purple
    pdf.set_text_color(*color)
    pdf.cell(200, 20, txt=f"ATS Match Score: {score}%", ln=True, align='C')
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)
    
    # --- FEEDBACK ---
    pdf.set_font("Arial", 'B', size=14)
    pdf.cell(200, 10, txt="AI Analysis & Feedback", ln=True)
    pdf.set_font("Arial", size=11)
    
    # Handle clean text
    clean_feedback = feedback.replace("*", "").replace("#", "")
    pdf.multi_cell(0, 7, txt=clean_feedback)
    pdf.ln(10)
    
    # --- SKILLS TABLE ---
    col_width = 90
    
    pdf.set_font("Arial", 'B', size=12)
    pdf.cell(col_width, 10, "Matched Skills", border=1)
    pdf.cell(col_width, 10, "Missing Skills (Critical)", border=1)
    pdf.ln()
    
    pdf.set_font("Arial", size=10)
    
    # Safety Check: Ensure lists are not None
    if resume_skills is None: resume_skills = []
    if missing_skills is None: missing_skills = []
    
    max_len = max(len(resume_skills), len(missing_skills))
    
    for i in range(max_len):
        m_skill = resume_skills[i] if i < len(resume_skills) else ""
        miss_skill = missing_skills[i] if i < len(missing_skills) else ""
        
        pdf.set_text_color(0, 100, 0) # Green for match
        pdf.cell(col_width, 8, m_skill, border=1)
        
        pdf.set_text_color(150, 0, 0) # Red for missing
        pdf.cell(col_width, 8, miss_skill, border=1)
        pdf.ln()
        
    pdf.set_text_color(0, 0, 0)
    pdf.ln(10)
    
    pdf.set_font("Arial", 'I', size=10)
    pdf.multi_cell(0, 5, "Note: This report was generated by AI. Please verify all details manually.")
    
    return pdf.output(dest='S').encode('latin-1')
