from fpdf import FPDF

def generate_pdf_report(username, role, score, feedback, resume_skills, missing_skills, category):
    class PDF(FPDF):
        def header(self):
            self.set_font('Arial', 'B', 15)
            self.cell(0, 10, 'NexHire Analysis Report', 0, 1, 'C')
            self.ln(5)
        def footer(self):
            self.set_y(-15)
            self.set_font('Arial', 'I', 8)
            self.set_text_color(128)
            self.cell(0, 10, 'Generated by NexHire', 0, 0, 'C')

    def sanitize_text(text):
        """Replaces incompatible unicode characters with ASCII equivalents."""
        replacements = {
            '\u2018': "'", '\u2019': "'",  # Smart quotes
            '\u201c': '"', '\u201d': '"',  # Smart double quotes
            '\u2013': '-', '\u2014': '-',  # Dashes
            '\u2022': '*',                 # Bullet points
            '\u2026': '...',               # Ellipsis
        }
        for char, replacement in replacements.items():
            text = text.replace(char, replacement)
        
        # Remove any remaining non-latin-1 characters
        return text.encode('latin-1', 'replace').decode('latin-1')

    pdf = PDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    # Sanitize inputs
    username = sanitize_text(username)
    role = sanitize_text(role)
    category = sanitize_text(category)
    feedback = sanitize_text(feedback)
    
    pdf.cell(200, 8, txt=f"Candidate: {username}", ln=True)
    pdf.cell(200, 8, txt=f"Target Role: {role}", ln=True)
    pdf.cell(200, 8, txt=f"Category: {category}", ln=True)
    pdf.ln(5)
    pdf.set_font("Arial", 'B', size=24)
    pdf.cell(200, 20, txt=f"Score: {score}%", ln=True, align='C')
    pdf.ln(5)
    pdf.set_font("Arial", size=11)
    
    # Use multi_cell for feedback to handle text wrapping
    pdf.multi_cell(0, 7, txt=feedback)
    
    return pdf.output(dest='S').encode('latin-1')
