import re
from fpdf import FPDF
import io

def extract_skills(text):
    # Basic keyword extraction (This would ideally use a proper NLP model or large skill database)
    # For now, we simulate extraction by looking for common tech/professional keywords
    common_skills = [
        "python", "java", "sql", "react", "aws", "docker", "kubernetes", "machine learning",
        "data analysis", "project management", "communication", "leadership", "agile", "scrum",
        "html", "css", "javascript", "typescript", "figma", "design", "marketing", "sales",
        "finance", "accounting", "hr", "recruiting", "tensorflow", "pytorch", "pandas", "numpy"
    ]
    
    found_skills = []
    text_lower = text.lower()
    
    for skill in common_skills:
        # Check for whole words to avoid partial matches
        if re.search(r'\b' + re.escape(skill) + r'\b', text_lower):
            found_skills.append(skill.title())
            
    return list(set(found_skills))

def generate_pdf_report(username, role, score, feedback, resume_skills, job_skills):
    class PDF(FPDF):
        def header(self):
            # Logo placeholder
            self.set_font('Arial', 'B', 15)
            self.cell(0, 10, 'NexHire Platinum Analysis Report', 0, 1, 'C')
            self.ln(5)

        def footer(self):
            self.set_y(-15)
            self.set_font('Arial', 'I', 8)
            self.set_text_color(128)
            # --- BRANDING FOOTER ---
            self.cell(0, 10, f'Generated by NexHire | Developed by Karunya K. P. | linkedin.com/in/karunyakp', 0, 0, 'C')

    pdf = PDF()
    pdf.add_page()
    
    # Title Section
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Candidate: {username}", ln=True)
    pdf.cell(200, 10, txt=f"Target Role: {role}", ln=True)
    pdf.ln(5)
    
    # Score Section
    pdf.set_font("Arial", 'B', size=24)
    color = (79, 70, 229) # Purple
    pdf.set_text_color(*color)
    pdf.cell(200, 20, txt=f"ATS Match Score: {score}%", ln=True, align='C')
    pdf.set_text_color(0, 0, 0)
    pdf.ln(10)
    
    # Feedback Section
    pdf.set_font("Arial", 'B', size=14)
    pdf.cell(200, 10, txt="AI Analysis & Feedback", ln=True)
    pdf.set_font("Arial", size=11)
    
    # Handle potentially long feedback text
    pdf.multi_cell(0, 7, txt=feedback.replace("*", "")) # Remove markdown bolding for PDF
    pdf.ln(10)
    
    # Skills Section
    matched = [s for s in resume_skills if s in job_skills]
    missing = [s for s in job_skills if s not in resume_skills]
    
    col_width = 90
    
    pdf.set_font("Arial", 'B', size=12)
    pdf.cell(col_width, 10, "Matched Skills", border=1)
    pdf.cell(col_width, 10, "Missing Skills", border=1)
    pdf.ln()
    
    pdf.set_font("Arial", size=10)
    
    # Find max length to iterate
    max_len = max(len(matched), len(missing))
    
    for i in range(max_len):
        m_skill = matched[i] if i < len(matched) else ""
        miss_skill = missing[i] if i < len(missing) else ""
        
        pdf.set_text_color(0, 100, 0) # Green for match
        pdf.cell(col_width, 8, m_skill, border=1)
        
        pdf.set_text_color(150, 0, 0) # Red for missing
        pdf.cell(col_width, 8, miss_skill, border=1)
        pdf.ln()
        
    # Reset text color
    pdf.set_text_color(0, 0, 0)
    pdf.ln(10)
    
    pdf.set_font("Arial", 'I', size=10)
    pdf.multi_cell(0, 5, "Note: This report was generated by AI. Please verify all details manually.")
    
    return pdf.output(dest='S').encode('latin-1')
